# For automatic lock on suspend/hibernation
systemctl --user import-environment DISPLAY

# Notification daemon
dunst &

# Composite manager, for blur and other neat effects
picom \
 --blur-method dual_kawase --blur-strength 2 --backend glx --glx-no-stencil \
 --fading --fade-in-step 0.05 --fade-out-step 0.1 \
 --corner-radius 10 --detect-rounded-corners \
 --rounded-corners-exclude 'class_g = "dwm"' \
 --rounded-corners-exclude 'window_type = "dock"' \
 --vsync --daemon

# Fonts
xset +fp "${XDG_FONTS:-$HOME/.local/share/fonts}"

# Disable mouse acceleration
xset m 0 0 &
xset r rate 300 50 &

xmodmap -e "clear lock"
xmodmap -e "keysym Multi_key = Multi_key Caps_Lock"
xmodmap -e "keycode 9 = Multi_key"
xmodmap -e "keycode 108 = Multi_key"
xmodmap -e "keycode 66 = Escape"

autorandr -c

feh --no-fehbg --bg-scale ~/pictures/background.png
dwmblocks &
xrdb $XDEFAULTS
exec /usr/local/bin/dwm
