#!/usr/bin/env sh

set -e

status="$(acpi -abi)" # get battery and adapter info

case $BLOCK_BUTTON in
  3) notify-send "Battery status" "$status" ;;
	4) brightnessctl -q s 10%+ ;;
	5) brightnessctl -q s 10%- ;;
esac

power=$(echo "${status}" | awk '/Battery [0-9]+: [A-Z]/{s+=$4;c++}; END{printf "%.1f%%", s/c}')

icon='?'
if [[ -z $(echo $status | sed -n '/on-line/p') ]]; then
  case "${power%.*}" in
    100 | 9[0-9]) icon='\uf578' ;;
    8[0-9]) icon='\uf581';;
    7[0-9]) icon='\uf580';;
    6[0-9]) icon='\uf57f';;
    5[0-9]) icon='\uf57e';;
    4[0-9]) icon='\uf57d';;
    3[0-9]) icon='\uf57c';;
    2[0-9]) icon='\uf57b';;
    1[0-9]) icon='\uf57a';;
    [0-9])  icon='\uf579';;
  esac
else
  icon='\uf583'
fi

echo -e "$icon $power"
